### ISSUE TITLE
msg_lines.h not part of the public repository

### ISSUE THREAD

**Issue by kappeler** [iralabdisco/kitti_player#2]
Compiling this package leads to the following error:

[100%] Building CXX object CMakeFiles/kitti_player.dir/src/kitti_player.cpp.o
/home/kama/catkin_ws/src/kitti_player/src/kitti_player.cpp:55:46: fatal error: road_layout_estimation/msg_lines.h: No such file or directory
 #include <road_layout_estimation/msg_lines.h>

**Comment by trigal** [comment]
Ok, I've created a "public" branch. Could you please try it?

**Comment by kappeler** [comment]
Thank you for your update.

There is at least one dependency missing:

catkin_ws/src/kitti_player/src/kitti_player.cpp:36:45: fatal error: ira_open_street_map/latlon_2_xy.h: No such file or directory
 #include "ira_open_street_map/latlon_2_xy.h"

**Comment by trigal** [comment]
thanks, updated. now the default branch is 'public'
